### ISSUE TITLE
Grass, leaves, foliage, and water become colorless when using Embeddium (Minecraft 1.20.1 NeoForged, Destroy 0.1.0 Snapshot 4)

### ISSUE THREAD

**Issue by Daxturus** [petrolpark/Destroy#440]
**Describe the bug**

On NeoForged 1.20.1, grass, water, and foliage textures turn completely gray if the game is loaded with Embeddium, when using the _latest snapshot version_ (Snapshot 4).

This does not occur with the previous stable version of Destroy, 0.0.8, both with and without Embeddium. This is most likely a new issue with the 0.1.0 snapshots.

**To Reproduce**

Steps to reproduce the bug:

1. Create a new instance of NeoForged 1.20.1 to be used for testing.
2. Install Create, Petrolpark's Library, and Destroy to that instance.
3. Create a new world to test. Grass should be the normal green color as you start the world; water should be blue. This is all good so far.
4. Close the game and add the Embeddium mod.
5. Restart the world with Embeddium; foliage and water should be a colorless gray-white.

**Expected Behavior/Screenshots**

Here is how the world should look. This is taken with Embeddium disabled and Destroy enabled.
![2024-09-26_17 36 53](https://github.com/user-attachments/assets/ee47d50a-db40-4b4b-a5b1-9de0a6ae5738)

And here is how it looks with Embeddium enabled. As you can probably tell, something is amiss; everything looks completely colorless.
![2024-09-26_17 35 49](https://github.com/user-attachments/assets/b1ce9725-f2fd-43d3-aba2-f7f427585cc6)

**System Information**

 - Minecraft 1.20.1 
 - NeoForge 47.1.106
 - Create 0.5.1h
 - Destroy 0.1.0, Snapshot 4
 - Petrolpark Lib 1.0.5
 - Embeddium 0.3.31

I am running these worlds on Debian using an Nvidia graphics card. I have had no similar issues in the past; everything from Acedium/Nvidium to shaders has worked for me without strange rendering issues.

**Additional context**

Here is a relevant log file, detailing the process of launching the game and loading a world with Embeddium and Destroy installed.
Lines 210-229 are particularly pertinent; these are Embeddium logs complaining that block color providers have been replaced.
[Destroy grass test log.txt](https://github.com/user-attachments/files/17156964/Destroy.grass.test.log.txt)
(Ignore the error on line 230 -- this is an issue with the Prism Launcher's flatpak version. This error occurs whenever I launch the game using the Prism Launcher, even when no mods are loaded.)

Embeddium alone does not produce this weird grass color bug; only when combined with the latest Destroy snapshot does the grass turn grayish white.

I am using the Prism launcher, in case that changes anything.
The world seed I've been using to get these screenshots is -9029979043972543010.

I discovered this bug when testing the modpack I've been working on. After updating, grass looked a consistent lifeless white-mint color. Unlike in the bare-bones test, the grass seems to have a slightly green tinge instead of being a dull neutral white. I think the difference in coloration might be caused by one of the other 200+ mods I have installed, though.

![2024-09-26_17 53 42](https://github.com/user-attachments/assets/d6f81375-1a30-466c-b297-cafb66cf4e24)
(Note that the grass should be a more saturated green, not this color.)

**Minecraft Username:** Daxturus

**Comment by CDWimmer** [comment]
Can confirm this also happens to me

**Comment by Penta0308** [comment]
![image](https://github.com/user-attachments/assets/99ac20ee-199e-4229-a3c6-f13bcc60533f)

Same issue with 0.1.0-snapshot-3.
1.20.1
Forge 43.3.7
Create 0.5.1h
Embeddium 0.3.31
Oculus 1.7.0 Loaded, with and w/o shader
(Shader is applied above mentioned things, i.e. smoothly shaded grey world.)
Windows 11, AMD Vega 8 (Ryzen 7530U iGPU)

**Comment by PinkDisorder** [comment]
Same issue happening with the exact same testing setup as Daxturus, except with forge instead of neoforge.

**Comment by GitHubAven** [comment]
I have a similar problem. Grass, leaves, foliage, and water become colorless on Xaeros Minimap.

**Comment by CDWimmer** [comment]
Noticed these log messages during start, maybe related:
```
[03:14:44] [Render thread/INFO] [Embeddium/]: Block minecraft:grass had its color provider replaced and will not use per-vertex coloring
[03:14:44] [Render thread/INFO] [Embeddium/]: Block minecraft:grass_block had its color provider replaced and will not use per-vertex coloring
[03:14:44] [Render thread/INFO] [Embeddium/]: Block minecraft:fern had its color provider replaced and will not use per-vertex coloring
[03:14:44] [Render thread/INFO] [Embeddium/]: Block minecraft:tall_grass had its color provider replaced and will not use per-vertex coloring
[03:14:44] [Render thread/INFO] [Embeddium/]: Block minecraft:tall_grass had its color provider replaced and will not use per-vertex coloring
[03:14:44] [Render thread/INFO] [Embeddium/]: Block minecraft:large_fern had its color provider replaced and will not use per-vertex coloring
[03:14:44] [Render thread/INFO] [Embeddium/]: Block minecraft:pink_petals had its color provider replaced and will not use per-vertex coloring
[03:14:44] [Render thread/INFO] [Embeddium/]: Block minecraft:oak_leaves had its color provider replaced and will not use per-vertex coloring
[03:14:44] [Render thread/INFO] [Embeddium/]: Block minecraft:jungle_leaves had its color provider replaced and will not use per-vertex coloring
[03:14:44] [Render thread/INFO] [Embeddium/]: Block minecraft:acacia_leaves had its color provider replaced and will not use per-vertex coloring
[03:14:44] [Render thread/INFO] [Embeddium/]: Block minecraft:dark_oak_leaves had its color provider replaced and will not use per-vertex coloring
[03:14:44] [Render thread/INFO] [Embeddium/]: Block minecraft:vine had its color provider replaced and will not use per-vertex coloring
[03:14:44] [Render thread/INFO] [Embeddium/]: Block minecraft:mangrove_leaves had its color provider replaced and will not use per-vertex coloring
[03:14:44] [Render thread/INFO] [Embeddium/]: Block minecraft:birch_leaves had its color provider replaced and will not use per-vertex coloring
[03:14:44] [Render thread/INFO] [Embeddium/]: Block minecraft:spruce_leaves had its color provider replaced and will not use per-vertex coloring
[03:14:44] [Render thread/INFO] [Embeddium/]: Block minecraft:water had its color provider replaced and will not use per-vertex coloring
[03:14:44] [Render thread/INFO] [Embeddium/]: Block minecraft:bubble_column had its color provider replaced and will not use per-vertex coloring
[03:14:44] [Render thread/INFO] [Embeddium/]: Block minecraft:water_cauldron had its color provider replaced and will not use per-vertex coloring
[03:14:44] [Render thread/INFO] [Embeddium/]: Block minecraft:sugar_cane had its color provider replaced and will not use per-vertex coloring
```

**Comment by petrolpark** [comment]
Should be fixed by https://github.com/petrolpark/Destroy/pull/447

**Comment by PinkDisorder** [comment]
The grey world issue was fixed in-world but persists on maps/minimaps.

**Comment by Penta0308** [comment]
Editing tint cache and patching every mods which require tinting can be a not good way.
A new way to tint locally is needed to solve all of the problems.

Also Distant Horizons gets the block tint color from biome directly. It can be made to use tint cache by mixin, but it will hurt performance.

**Comment by Daxturus** [comment]
![2024-09-28_12 41 47](https://github.com/user-attachments/assets/c2b94bd9-a123-406e-893f-fe9439afd785)

Grass color appears fixed in Snapshot 5, but map colors are still broken.
